// Generated by CrewAI Kotlin API Architect
rootProject.name = "twitter-clone-backend"

include("user-service") 
include("post-service")

// Future services (ready for expansion):
// include("timeline-service")
// include("notification-service")
// include("gateway-service")
